"""empty message

Revision ID: f8f3e7112a5e
Revises: 
Create Date: 2022-08-18 00:20:21.649956

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f8f3e7112a5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('type', sa.String(length=20), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_type'), 'user', ['type'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('quiz',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pin', sa.String(length=64), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index(op.f('ix_quiz_pin'), 'quiz', ['pin'], unique=True)
    op.create_table('question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question', sa.String(length=255), nullable=True),
                    sa.Column('type', sa.String(length=20), nullable=True),
                    sa.Column('choice_a', sa.String(length=255), nullable=True),
                    sa.Column('choice_b', sa.String(length=255), nullable=True),
                    sa.Column('choice_c', sa.String(length=255), nullable=True),
                    sa.Column('choice_d', sa.String(length=255), nullable=True),
                    sa.Column('answer', sa.String(length=255), nullable=True),
                    sa.Column('quiz_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_index(op.f('ix_question_answer'), 'question', ['answer'], unique=False)
    op.create_index(op.f('ix_question_choice_a'), 'question', ['choice_a'], unique=False)
    op.create_index(op.f('ix_question_choice_b'), 'question', ['choice_b'], unique=False)
    op.create_index(op.f('ix_question_choice_c'), 'question', ['choice_c'], unique=False)
    op.create_index(op.f('ix_question_choice_d'), 'question', ['choice_d'], unique=False)
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=False)
    op.create_index(op.f('ix_question_type'), 'question', ['type'], unique=False)
    op.create_table('score',
                    sa.Column('quiz_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('quiz_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_index(op.f('ix_question_type'), table_name='question')
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_index(op.f('ix_question_choice_d'), table_name='question')
    op.drop_index(op.f('ix_question_choice_c'), table_name='question')
    op.drop_index(op.f('ix_question_choice_b'), table_name='question')
    op.drop_index(op.f('ix_question_choice_a'), table_name='question')
    op.drop_index(op.f('ix_question_answer'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_quiz_pin'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
